# Site settings
title: Marco Bonardo
email: blog@bonardo.net
description: > # this means to ignore newlines until "baseurl:"
  Blog of Marco Bonardo, IT consultant and technology enthusiast. Working with open source for the Web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mak77.github.io" # the base hostname & protocol for your site
twitter_username: mak77
github_username:  mak77
avatar: https://avatars1.githubusercontent.com/u/1581117?v=3&s=140
disqus: MaK

author:
  fullname: Marco Bonardo
  github: mak77
  twitter: mak77
  disqus: MaK

# Build settings
timezone: Europe/Rome
markdown: kramdown
encoding: utf-8

# Use the following plug-ins
gems:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
